language: perl
perl:
  - "5.20"
  - "5.16"
  - "5.10"
install:
  - "cpanm -n Test::Pod Test::Pod::Coverage"
  - "cpanm -n --installdeps ."
script_DISABLED: "perl Makefile.PL && make test TEST_VERBOSE=1"
notifications:
  email: false
